
export default class VirtualPetsStrings {
#Generated by Eclipse Messages Editor (Eclipse Babel)

APPLICATION_NAME = PrettyPets

ARE_YOU_REALLY_WANT_TO_CLOSE_SESSION_AND_EXIT = Are you really want to close session and exit?

AUTHOR = Author

BIRHDATE = Birthdate

BOOKCASE = bookcase

CANCEL = Cancel

CAN_NOT_ADD_ICON_TO_SYSTEM_TRAY = Can not add icon to system_tray.

CHAT_STARTED = Chat started

CITY = City

CLOSE_CHAT_TAB = Close chat tab

CLOSE_SESSION_AND_EXIT = Close session and exit

CLOSING_SESSION = Closing session...

COMMENT = Comment

CONSOLE_IS_AVAILABLE = Console is available.

COUNTRY = Country

CREATE_PET = Create pet

DATETIME_IS = Date/time is %tY-%<tm-%<td %<tH:%<tM (%<td %<tB %<tY).

DELETE_PET = Delete pet

DRESSING_ROOM_HOW_TO_PLAY_1 = Welcome to dressing room.

DRESSING_ROOM_HOW_TO_PLAY_2 = Here you can customize cloth of your pet.

DRESSING_ROOM_HOW_TO_PLAY_3 = You can earn new clothes in the treasury.

DRINK = Drink

EMAIL = e-mail

ERASE_CHAT_TAB = Erase chat tab

ERROR = Error

EXIT = Exit

EXP = Exp

EXPERIENCE = Experience

Experience = Experience

FEED = Feed

FILL_NAME = Fill name.

HIDDEN_OBJECTS_GAME_OVER_1 = Game over.

HIDDEN_OBJECTS_GAME_OVER_2 = Your reward is:

HIDDEN_OBJECTS_GAME_OVER_3 = -

HIDDEN_OBJECTS_HOW_TO_PLAY_1 = Players should find objects, that displayed in four

HIDDEN_OBJECTS_HOW_TO_PLAY_2 = blue squares on bottom screen. Press to found object

HIDDEN_OBJECTS_HOW_TO_PLAY_3 = to collect it.

HIDDEN_OBJECTS_WAITING_PLAYER = Waiting for player...

HIDDEN_OBJECTS_WAITING_PLAYERS_1 = Waiting for players. You can press "Play", to start game

HIDDEN_OBJECTS_WAITING_PLAYERS_2 = with already connected players.

INCOMPATIBLE_VERSION = You need to download client version %s.

INSUFFICIENT_RESOURCES = Not enough resources

LETTER_SUCCESSFULLY_SENDED = Letter successfully sended.

LEVEL = Level

LOGIN = Login

LOGIN_BY = Login by...

LOOK_AND_FEEL = Look and feel

LVL = Lvl

MAIN_CHAT = Main chat

MOVE = Move

NAME = Name

NAME_IS_BUSY = Name is busy.

NEW_ACHIEVEMENT = Achievement unlocked:

NOT_SELECTED = Not selected

NO_PATH = No path to that place.

OK = OK

PASSWORD = Password

PLAY = Play

PRETTY_CHAT = Pretty Chat

PROXY_PORT = Proxy port

PROXY_SERVER = Proxy server

PROXY_SETTINGS = Proxy settings

REFRESH = Refresh

REFRIGERATOR = refrigerator

REGISTER = Register

RESTORING_SESSION = Restoring session...

REVIVE_PASSWORD = I forgot password

SAY = Say

SAY_PRIVATE = Say private

SELECT_FOTO = Select foto

SEND_REVIVE_EMAIL_LETTER = Send revive email letter

SERVER = Server

SETTINGS = Settings

SEX = Sex

SEX_MAN = Man

SEX_WOMAN = Woman

SOUND = Sound

STATUS = Status

TEACH = Teach

THIS_BUILDING_IS_MAX_LEVEL = This building is max level.

TYPE = Type

UPGRADE = Upgrade

USE = Use

USERS_ONLINE = Users Online

USER_INFORMATION = User information

USER_PETS = User Pets

WATER_SOURCE = water source

YOU_HAVE_REACHED_LEVEL = You have reached level %s.

}